id: P000715
initial_creation_type: ocr
created_at: 30/03/2020
last_modified_at: 2021-12-16 16:38:39.558230
source_metadata:
  id: bdr:W1KG5375
  title: བོད་ཀྱི་གསོ་བ་རིག་པ་ལས་སྨན་རྫས་སྦྱོར་བཟོའི་ལག་ལེན་གསང་སྒོ་འབྱེད་པའི་ལྡེ་མིག་
  author: ''
  volumes:
    22843cf384b942cb9fc9cebb30aefb05:
      image_group_id: I1KG5391
      title: ''
      volume_number: 1
      total_pages: 562
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: true
